name: localdev-neo4j

services:
  neo4j:
    image: neo4j:2025.12.1
    container_name: neo4j-server
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    volumes:
      - ${NEO4J_VOLUME_DIR}/data:/data
      - ${NEO4J_VOLUME_DIR}/logs:/logs
      - ${NEO4J_VOLUME_DIR}/import:/import
      - ${NEO4J_VOLUME_DIR}/plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - neo4j-network
    healthcheck:
      test: [ "CMD-SHELL", "cypher-shell -u ${NEO4J_USERNAME} -p ${NEO4J_PASSWORD} \"RETURN 1;\" >/dev/null" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  neo4j-network:
    name: neo4j-network
